#!/usr/bin/env python-linux中指定脚本的解释程序
# -*- coding: cp936 -*-
#guessrandom.py by meilizhang,2017/2/22
#This programe is guessing the random in 1 to 100, referfing the programe on youtube
import random

def main():
  #generate random integer in 1 to 100 and get user input
  randomNum = random.randint(1,100)
  userNum = input("please enter any number:")

  #compare the user input to random for loop
  while(userNum != randomNum):
    if userNum > randomNum:
      print "you got higer"
      userNum = input("please enter any number:")
    else:
      print "you got lower"
      userNum = input("please enter any number:")

  #got the random
  print "congratulation, you got it! "
    



if __name__ == "__main__":
  main()
